name: Rixor
main: com.projectrixor.rixor.scrimmage.Rixor
version: 1.3
depend: [WorldEdit]
author: ProjectRixor Team
load: STARTUP
commands:
  setteam:
    aliases: [st]
    description: Set the name of a team.
  setnext:
    aliases: [sn]
    description: Set the next map.
  end:
    aliases: [cancel]
    description: Stop/End the game.
  start:
    description: Start the game starting timer.
  staff:
    description: Lists off the staff.
  help:
    description: Help on ParaPGM/Rixor commands.
  request:
    description: Send a request to online staff.
  match:
    aliases: [info,next,map]
    description: Check the map status.
  test:
    description: so yeah tests woo.
