name: Rixor
main: com.projectrixor.rixor.scrimmage.Rixor
version: 1.3
depend: [WorldEdit]
author: ProjectRixor Team
load: STARTUP
commands:
  setteam:
    aliases: [st]
    description: Set the name of a team.
  setnext:
    aliases: [sn]
    description: Set the next map.
  end:
    aliases: [cancel]
    description: Stop/End the game.
  start:
    description: Start the game starting timer.
  staff:
    description: Lists off the staff.
  help:
    description: Help on ParaPGM/Rixor commands.
  request:
    description: Send a request to online staff.
  match:
    aliases: [info,next,map]
    description: Check the map status.
  test:
    description: so yeah tests woo.
  report:
    description: Files a report against a player for staff to investigate.
    permission: rixor.staff
    usage: /report <playername> <message>

permissions:
  rixor.staff:
    default: false
    description: Staff need this to get the report that a player files.